### PR TITLE
Setup and add first tests, rewrite app.py a few

### PR DESCRIPTION
**Pull request by chinskiy**
Hi @OrkoHunter 
I've add first tests to project and run them on Travis CI
My [PR](https://github.com/chinskiy/pep8speaks/pull/1)
Now u can add Travis CI to this repo and here will be first tests :tada: 

I've fast check pep8speaks and seems like it's works as expected but additional testing would be helpful

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Hello @chinskiy !

Thanks for taking up tests ! In #57 I am in process of refactoring a lot of internal functions. I'll try to get that merged by this weekend. I will not add any tests in #57 and we can work on them in this PR only after that PR is done.

**Comment by chinskiy** [comment]
Hi @OrkoHunter 
Sure, I will wait until #57 will be merged.
I saw that there is a lot of changes and after that I will actualize this PR

**Comment by OrkoHunter** [comment]
That's awesome !

**Comment by OrkoHunter** [comment]
Hello @chinskiy 

I have merged #57 and tested in production. Please rebase this PR with the current master.
I have also enabled Travis for this repository. And since the master contains .travis.yml file, this PR will contain the build status.

Let's write tests !

**Comment by chinskiy** [comment]
Hi @OrkoHunter I've update PR

also I was thinking about tool to see code coverage metric like [Codecov](https://github.com/marketplace/codecov) 
If u agree I will make another PR with this tool integration

**Comment by OrkoHunter** [comment]
I really like landscape.io with no comments permission. Codecov is also
good but bit noisy.

**Comment by chinskiy** [comment]
For me it's not matter what tool it will be
I'm ok with landscape.io too if it have code coverage reports. Think it's important metric.

**Comment by chinskiy** [comment]
Greetings @OrkoHunter 
What with this PR? 
Wait for review

**Comment by OrkoHunter** [comment]
Hey @chinskiy,
This looks good. I was not sure if the PR is ready to merge or not because of some `#todos`. Will merge it tonight.

**Comment by OrkoHunter** [comment]
Heroku lets us deploy an app for each Pull Request. This is great. I deployed it and tested on the [`test-repository`](https://github.com/orkohunter/test-pep8speaks) as well.

Awesome job @chinskiy :tada:

**Pull request merged**
