### PR TITLE
PR: Improve wording of comments and refactor, and fix other minor text issues throughout the package

### LINKED ISSUE #90: Improvements in comment text
Hey, I'm one of the Spyder core dev team members and we love PEP8Speaks! Having previously worked as a writer and copyeditor, the grammar, spacing, redundancy and clarity of the comment text could be improved:

### Current version

Hello {username} !  Thanks for {submitting/updating} the PR.

- In the file [`spyder/app/tests/test_mainwindow.py`](https://github.com/spyder-ide/spyder/blob/f0e4b7e477b997538dd6ef66f8344a220881d1bd/spyder/app/tests/test_mainwindow.py), following are the PEP8 issues :

> [Line 1578:1](https://github.com/spyder-ide/spyder/blob/f0e4b7e477b997538dd6ef66f8344a220881d1bd/spyder/app/tests/test_mainwindow.py#L1578): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 1590:80](https://github.com/spyder-ide/spyder/blob/f0e4b7e477b997538dd6ef66f8344a220881d1bd/spyder/app/tests/test_mainwindow.py#L1590): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)

 - In the file [`spyder/plugins/history.py`](https://github.com/spyder-ide/spyder/blob/f0e4b7e477b997538dd6ef66f8344a220881d1bd/spyder/plugins/history.py), following are the PEP8 issues :

> [Line 220:9](https://github.com/spyder-ide/spyder/blob/f0e4b7e477b997538dd6ef66f8344a220881d1bd/spyder/plugins/history.py#L220): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

### Suggested alternative

Hello {username}!  Thanks for {submitting/updating} this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008/) issues, and found:
* In the file [`spyder/app/tests/test_mainwindow.py`](https://github.com/spyder-ide/spyder/blob/f0e4b7e477b997538dd6ef66f8344a220881d1bd/spyder/app/tests/test_mainwindow.py):

> [Line 1578:1](https://github.com/spyder-ide/spyder/blob/f0e4b7e477b997538dd6ef66f8344a220881d1bd/spyder/app/tests/test_mainwindow.py#L1578): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 1590:80](https://github.com/spyder-ide/spyder/blob/f0e4b7e477b997538dd6ef66f8344a220881d1bd/spyder/app/tests/test_mainwindow.py#L1590): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)

* In the file [`spyder/plugins/history.py`](https://github.com/spyder-ide/spyder/blob/f0e4b7e477b997538dd6ef66f8344a220881d1bd/spyder/plugins/history.py): No issues found.

### No errors message

Also, to make the followup message a little more clear and correct, it could be changed from

Cheers ! There are no PEP8 issues in this Pull Request. :beers:

to

There are no [PEP 8](https://www.python.org/dev/peps/pep-0008/) issues in this Pull Request. Cheers! :beers:

I can submit a quick PR to do this. Thanks!

In general, as a tip for the future keep in mind that just like in Python/PEP 8. there should be a space before punctuation (exclamation points, colons, etc) and not after.

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Fixes #90 .

See that issue for more details on the proposed content changes and rationale. Additionally, I refactored a lot of the code within the ``prepare_comment()`` function to be cleaner and easier to maintain, and cleaned up the pylint and PEP 8 (heh) issues.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
@OrkoHunter Its been two months since I've submitted this PR, with no response or activity since. Is this project still alive? If not, is there an active fork I can submit this to?

**Comment by CAM-Gerlach** [comment]
Updated with some minor refinements.

> In the file pep8speaks/helpers.py, following are the PEP8 issues [sic]

>> Line 161:32: W605 invalid escape sequence '\d'

I didn't touch this line, so not sure why its complaining.

**Comment by OrkoHunter** [comment]
@CAM-Gerlach This is an incredible change. Thank you for working on this!

The project does not have a solid test framework, hence it is extremely difficult to review changes which make critical changes. This, along with my final year timeline of college, delayed this Pull Request. I would like to apologize for it and assure that it was not intentional.

Question: What does `!s` do while formatting text? e.g. `f"{action_text!s}"`

**Comment by CAM-Gerlach** [comment]
> I would like to apologize for it and assure that it was not intentional.

No worries. As much as we all like to bash maintainers sometimes if they don't do what we want right away, you're not only helping us out providing this code but to begin with, but also helping host it as a service for others to use even more easily, and its been a major help to us on PRs irrespective of the minor semantic irregularities. And there's always that "fork" button if the project is truly dead...glad you got through all that okay and such is not the case!

> Question: What does `!s` do while formatting text? e.g. `f"{action_text!s}"`

@OrkoHunter [Coerces the result to a string with str()](https://docs.python.org/3/library/string.html#grammar-token-conversion).

Based on what I know now (given this PR was actually submitted closer in time to when I actually starting seriously getting into Python than to the present day, haha), I doubt its strictly necessary where I used it (I used to think it was necessary to coerce non-string types, but its not really, it just tells Python to use ``str()`` instead of ``repr()``, ``ascii()`` or whatever else is specified by ``__format__()`` by default), unless there was a specific reason I wanted that repr. I doubt it (its been so long I can't remember and would have to look over the code in more detail) but it doesn't actually do any harm.

**Comment by OrkoHunter** [comment]
Thank you @CAM-Gerlach for your words. It made my day :)

This is good to go. 🎉

**Pull request merged**
