### PR TITLE
Separate default config into a file

### PR DESCRIPTION
**Pull request by OrkoHunter**
The default configuration was hard coded inside the helpers module. Keeping it as a separate file is a better idea and will help refer to it in a more permanent way. (Earlier the line numbers were being used, which kept changing)

### CODE REVIEW

**Comment by chinskiy** [comment]
Nice!
Also think to do PR with this changes

**Comment by chinskiy** [comment]
But also I was thinking to move these messages to default config
https://github.com/OrkoHunter/pep8speaks/blob/master/pep8speaks/helpers.py#L211

**Comment by OrkoHunter** [comment]
@chinskiy Yep that should also be done. I'll push the changes.

**Comment by OrkoHunter** [comment]
This looks good! Merging

**Pull request merged**
